# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from installed_protos.v1 import api_pb2 as installed__protos_dot_v1_dot_api__pb2


class APIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSomething = channel.unary_unary(
            "/APIService/GetSomething",
            request_serializer=installed__protos_dot_v1_dot_api__pb2.SimpleAPIleMessage.SerializeToString,
            response_deserializer=installed__protos_dot_v1_dot_api__pb2.SimpleAPIleMessage.FromString,
        )


class APIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSomething(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_APIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSomething": grpc.unary_unary_rpc_method_handler(
            servicer.GetSomething,
            request_deserializer=installed__protos_dot_v1_dot_api__pb2.SimpleAPIleMessage.FromString,
            response_serializer=installed__protos_dot_v1_dot_api__pb2.SimpleAPIleMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "APIService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class APIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSomething(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/APIService/GetSomething",
            installed__protos_dot_v1_dot_api__pb2.SimpleAPIleMessage.SerializeToString,
            installed__protos_dot_v1_dot_api__pb2.SimpleAPIleMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
